version: "3"
services:
  app:
    build: .
    container_name: dx2021_camimage_share_app
    ports:
      - 88:80
    environment:
      - publicKeyPath=/work/secret/secret.pem.pub
      - privateKeyPath=/work/secret/secret.pem
    volumes:
      - /home/cam/storage/Image:/work/image
      - /home/cam/storage/Inference:/work/inference
      - /home/cam/secret:/work/secret
      - /home/cam/storage/Config:/work/config
    networks:
      dxNetwork-1:
        ipv4_address: 192.1.1.3
networks:
  dxNetwork-1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.1.1.0/24