version: "3"
services:
  app:
    build: .
    container_name: dx2021_camimage_share_app
    ports:
      - 88:80
    volumes:
      - /home/cam/storage/Image:/work/Image
      - /home/cam/storage/Inference:/work/Inference
      - /home/cam/storage/Config:/work/Config
    networks:
      dxNetwork-1:
        ipv4_address: 192.1.1.3
networks:
  dxNetwork-1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.1.1.0/24