name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: dx_deploy_id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: |
          Host server
            HostName 118.27.110.225
            User deploy
            IdentityFile ~/.ssh/dx_deploy_id_rsa
    - name: Run Deploy Script
      run: |
        ssh server"
        cd dx2021_camImage_share &&
        git pull origin main &&
        docker-compose build &&
        docker-compose down &&
        docker-compose up -d"